export HADOOP_HOME=/app/hadoop-3.0.0
export HADOOP_CONF_DIR="$HADOOP_HOME"/etc/hadoop
export HADOOP_MAPRED_HOME="$HADOOP_HOME"
export HADOOP_COMMON_HOME="$HADOOP_HOME"
export HADOOP_HDFS_HOME="$HADOOP_HOME"
export YARN_HOME="$HADOOP_HOME"
export HADOOP_COMMON_LIB_NATIVE_DIR="$HADOOP_HOME"/lib/native
export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib"

export JAVA_HOME=/app/jdk1.8.0_162
export PATH="${JAVA_HOME}/bin:${HADOOP_HOME}/bin${PATH:+:}${PATH}"

